name: SU95X Livery Package Release
on:
  push:
    tags:
      - 'v*'
      - '!v*-alpha*'
      - '!v*-beta*'
      - '!v*-rc*'
    paths:
      - '.github/workflows/su95x-livery-package-release.yml'
      - 'hdw-su95x-liveries/**'
      - 'scripts/build-su95x-liveries.js'
      - 'scripts/build-su95x-liveries.sh'
      - 'igniter.config.mjs'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build-ingamepanels-checklist-fix:
    # Prevent running this on forks
    if: github.repository_owner == 'headwindsim'
    name: 'Build su95x Livery Package'
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      ZIP_NAME: hdw-su95x-liveries-release.zip
      BUILD_DIR_NAME: release
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo A32NX_PRODUCTION_BUILD=1 >> .env
          echo CLIENT_ID=${{ secrets.NAVIGRAPH_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.NAVIGRAPH_CLIENT_SECRET }} >> .env
          echo CHARTFOX_SECRET=${{ secrets.CHARTFOX_SECRET }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
      - name: Setup Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
      - name: Copy Sources
        run: |
          ./scripts/dev-env/run.sh ./scripts/copy.sh
      - name: Build SU95X Livery Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/build-su95x-liveries.sh --no-tty -j 4
      - name: Build ZIP files
        run: |
          ./scripts/dev-env/run.sh node ./scripts/fragment-su95x-liveries.js
          cp ./hdw-su95x-liveries/out/build-modules/modules.json ./hdw-su95x-liveries/out/headwindsim-su95x-livery-package/install.json
          ./scripts/dev-env/run.sh node ./scripts/install-source-su95x-liveries.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./hdw-su95x-liveries/out/
          zip -r ../../${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME }} ./headwindsim-su95x-livery-package/
          cd ../../
      - name: Upload to CloudFlare CDN
        env:
          CLOUDFLARE_WORKER_PASSWORD: ${{ secrets.CLOUDFLARE_WORKER_PASSWORD }}
          CDN_BUCKET_DESTINATION: addons/su95x-livery-package/release
        run: |
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./hdw-su95x-liveries/out/build-modules